### ISSUE TITLE
Call to :ImportName hangs

### ISSUE THREAD

**Issue by satshabad-cr** [mgedmin/python-imports.vim#7] opened 2020-05-14 16:10 UTC
Sorry that was the world's worst issue description.

Hmm, how would I give you steps to reproduce? I'm afraid I can't upload my tag file as it's from work.

It's 11mb though if that helps

I use all the default settings of this plugin.

My laptop starts whirring after I let it hang

Do you have any commands I might be able to run to give you more info?

**Comment by mgedmin** [comment] 2020-05-14 17:37
I need more information.  Steps to reproduce the problem would be best.

**Comment by wjordan213** [comment] 2020-05-14 18:28
^^ also experiencing this issue

**Comment by wjordan213** [comment] 2020-05-14 18:29
typing `:ImportName <TagName>` in my repo, I'm able to select an item, and after that selection the hanging occurs. If I ctrl-c out of it I'll actually end up with a split pane into the file that the tag was being pulled from.

**Comment by satshabad-cr** [comment] 2020-05-14 18:31
I updated the description

**Comment by wjordan213** [comment] 2020-05-14 18:38
![python-vim](https://user-images.githubusercontent.com/3341862/81972359-783a5580-95f0-11ea-83a1-82d6ea540d82.gif)

**Comment by satshabad-cr** [comment] 2020-05-14 18:48
Oh, mine is hanging much longer... indefinitely

**Comment by wjordan213** [comment] 2020-05-14 18:50
^^ yeah that was after ctrl-c-ing out of it

**Comment by mgedmin** [comment] 2020-05-14 19:05
> typing :ImportName <TagName> in my repo, I'm able to select an item, and after that selection the hanging occurs. If I ctrl-c out of it I'll actually end up with a split pane into the file that the tag was being pulled from.

Ok, that means the hang is happening somewhere between the `exec "noautocmd stjump ..."` and the `close` in
https://github.com/mgedmin/python-imports.vim/blob/7c4c27bd6aaa22c7ec1e2adda19e928702749c0e/plugin/python-imports.vim#L289-L313

Would you mind adding some `:echomsg "got to here 1/2/3"`, or maybe using Vim's builtin script debugger to single-step though that function to see where the hang is occurring?

If you could reproduce the problem on some open-source project, that would be ideal, because I'd love to be able to reproduce it here.

And can you confirm that this only happens you try a tag with multiple definitions (because that's the only way you get the selection menu)?

**Comment by satshabad-cr** [comment] 2020-05-14 19:37
I'll try what you suggest when I get a second, but I wanted to say that I
never get to the selection menu at all- it hangs when I hit enter

**Comment by mgedmin** [comment] 2020-05-14 19:50
> I'll try what you suggest when I get a second, but I wanted to say that I
never get to the selection menu at all- it hangs when I hit enter

In which case it might be hanging sooner, or later.

Oooh, I wonder if it's this loop:
https://github.com/mgedmin/python-imports.vim/blob/6011cd8a677245302fd14bbb54a3e3dbd8e5854b/autoload/pythonimports.vim#L19-L30

**Comment by mgedmin** [comment] 2020-05-14 19:51
Heh, I can reproduce the problem, if I actually `git pull` and use the latest code.

Because I merged a PR without testing it myself, after trusting that the submitter did so.

**Comment by mgedmin** [comment] 2020-05-14 19:52
Can you test the fix in git master?  If you still suffer from this bug, please reopen.

**Closed as completed** 2020-05-14 19:52 UTC
Labels: bug

**Comment by wjordan213** [comment] 2020-05-14 19:56
This works for me now! Thanks for the responsiveness here

**Comment by mgedmin** [comment] 2020-05-14 19:58
> Because I merged a PR without testing it myself, after trusting that the submitter did so.

TBH the buggy code is my own -- I suggested it while reviewing the PR in question. :D

**Comment by satshabad-cr** [comment] 2020-05-14 21:30
Fixed for me! Thanks!

And thank a TON for creating and maintaining this plugin, there's really not much else that does this and I find it SUPER useful every day. Been using it for years.

Cheers!
